### ISSUE TITLE
List disappears after mouse-over when attached to worldmap 

### ISSUE THREAD

**Issue by Gendji** [Amadeus-/Broker_WorldQuests#20]
After the update from 11.0.2.13 to 11.0.2.14 a "bug" appeared that is still there in 11.0.2.15.

I have the list attached to the world map and normally it stays visible until i close the map, regardless of where the mouse pointer is.

With the new versions, the list disappears when i mouse-over the quests and move my mouse outside the frame list. The map itself is still there.

I have to close and open the map to see the list again.

After installing 11.0.2.13 again this behavior is like it always was. 

I could not find any setting that handles this behavior so i think it is a bug?

**Comment by Gendji** [comment]
![Broker Attach Worldmap](https://github.com/user-attachments/assets/47fb782f-db02-447d-94cc-57b375cab982)

As you can see i use the "attach list frame to world map" option which makes the list appear next to the world map. It normally stays there regardless of where the mouse is.

After the updates, the list disappears if the mouse goes outside the list.

This changed after the 11.0.2.14 update, 11.0.2.13 is working like before.

**Comment by Amadeus-** [comment]
@Gendji 
----
Try this the version that I've attached.  (Just replace your current /Interface/Addons/Broker_WorldQuests with what's in this zip file.)  

From my testing it seems fixed with this version, but just wanted to double-check that it's fixed exactly your issue.
[Broker_WorldQuests.zip](https://github.com/user-attachments/files/16986728/Broker_WorldQuests.zip)

**Comment by Gendji** [comment]
It works! 

That was a very quick fix, thank you!
